name="words-a-day-app"
compatibility_date="2026-06-28"

[[d1-databases]]
binding="WORDS_DB"
database_name="words-a-day-db"
database_id="words-a-day-db"

[[kv-namespaces]]
binding="WORDS_KV"
id="VOCABUILDER_KV" 

[[queues.producers]]
queue="words-harvest-queue"
binding="HARVEST_QUEUE"

[[queues.consumers]]
queue="words-harvest_queue"
max_batch_size=10
max_batch_timeout=5
